volumes:
    torkdata:

networks:
    hpw-net:
        driver: bridge
        internal: false

services:
    postgres:
        container_name: postgres
        image: postgres:15.3
        restart: always
        environment:
            POSTGRES_USER: tork
            POSTGRES_PASSWORD: tork
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: tork
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U tork -d tork" ]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - torkdata:/var/lib/postgresql/data
        networks:
            - hpw-net

    hpw-server:
        build:
            context: .
            dockerfile: Dockerfile.main
        image: hpw-server
        restart: always
        ports:
            - "8000:8000"
            - "80:80"
        environment:
            - DOCKER_API_VERSION=1.43
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - hpw-net


